### ISSUE TITLE
Error when trying to use in STA mode

### ISSUE THREAD

**Issue by luxlux** [Vitorbnc/espSuite#1]
Thanks for your project, it looks like to be what i need to talk to my thermal receipt printer via WebSocket.
It took me a while to understand how to install it and to set it up.

Anyhow, now in AP mode seems to work as it should. (i still have not connected it to my serial device, but if I connect TX & RX together and connect to the ESP01 using WebSocket, i get the echo of what I send to it.)

But i need it not in AP mode. I need it in STA mode.

I configure it as follows:
I go to 192.168.1.1 with Chrome and set the SSID and password in the STATION box, then press submit. Also I go to the next box, there i select "Station" & "Debug". Also I put 230400 into the "Serial baud rate" field and press submit.

When i now reboot the ESP-01, the WIFI will not joined.
Instead i get the following in Serial Monitor:
Exception (28):
epc1=0x4000c007 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

Error Stack:
>>>stack>>>
3fff2c50:  402010ae 3fff0b50 3fff0bac 40207dfe  
3fff2c60:  3fffdad0 3fff2d44 3fff0bac 402092e4  
3fff2c70:  00000000 00000000 00000000 00000000  
3fff2c80:  3fff0570 3fff1b74 3fff1d00 3fff1b74  
3fff2c90:  3fffdad0 3fff1c38 40211594 3fff1c38  
3fff2ca0:  3fffdad0 3fff2d44 3fff0bac 40209642  
3fff2cb0:  3fffdad0 3fff2d44 3fff0bac 40209b2d  
3fff2cc0:  feefeffe feefeffe feefeffe feefeffe  
3fff2cd0:  00000000 00000000 00000000 3fff4db4  
3fff2ce0:  3fff4e0c feefeffe feefeffe feefeffe  
3fff2cf0:  feefeffe feefeffe feefeffe 3fff1cf4  
3fff2d00:  3fffdad0 00000000 3fff1ced 402115d8  
3fff2d10:  feefeffe feefeffe 3fff1d00 40100718  
<<<stack<<<

EspExceptionDecoder translates this to:

```
0x402010ae: delay at /Users/lutz/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/core_esp8266_wiring.c line 53
0x40207dfe: findKey  at /Users/lutz/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson/JsonObject.hpp line 302
:  (inlined by) ArduinoJson::Internals::JsonVariantAs ::type ArduinoJson::JsonObject::get_impl (char const*) const at /Users/lutz/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson/JsonObject.hpp line 308
0x402092e4: loadInit() at /Users/lutz/Documents/Arduino/EespSuite/EespSuite.ino line 363
0x40211594: esp_yield at /Users/lutz/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/core_esp8266_main.cpp line 56
0x40209642: setupWiFi() at /Users/lutz/Documents/Arduino/EespSuite/EespSuite.ino line 468
0x40209b2d: setup at /Users/lutz/Documents/Arduino/EespSuite/EespSuite.ino line 103 (discriminator 2)
0x402115d8: loop_wrapper at /Users/lutz/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/core_esp8266_main.cpp line 56
0x40100718: cont_norm at /Users/lutz/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/cont.S line 109
```

[esp8266 Exception list](https://github.com/esp8266/Arduino/blob/master/doc/exception_causes.rst) says Exception 28 means "LoadProhibitedCause | A load referenced a page mapped with an attribute that does not permit loads"

Do you have an idea why the station mode does not work?
Have you tested it? Does it work with you?

Lutz

**Comment by luxlux** [comment]
I tried now much more long.

I found out, the problem does NOT depend on which WIFI mode is used!
I have made the configuration now in the json files before uploading them to the device. So i have set it to STA mode. Doing so, this error does not apply!

But if I change the protocol settings using the webinterface the device, after reboot the device throws an exception. also if i set it to AP mode.

So the problem seems to be the reading of the JSON, which was written using the webinterface.
If the JSON will be read instead from the uploaded file, this problem will not happen.

What can be the reason for this? The organisation of the memory? The flash mode? Possibly the voltage? (it get's power from the USB of my mac.)

I use a black ESP01 module with 1MB (64k SPIFFS), Flashmode: QIO

For getting power (over USB), flashing and testing I have hooked the device on an NodeMCU board, which is hold in reset mode, to forward its serial port to the ESP01.

**Comment by Vitorbnc** [comment]
Hey, luxlux.
I'm glad to hear this code was helpful. Yes, I've tested the different modes, and currently use TCP socket for fast communication between devices.
It's been some time since I've uploaded the code to an ESP8266, so I'm not sure wheter it plays nice with the latest ArduinoJson versions. 
Try changing upload settings on Arduino IDE or editing the json files. If that doesn't help, try an older version of that library.

**Comment by luxlux** [comment]
I'v tried both now. Using the more than 8 month old ArduinoJson 5.8.4 and also flashing in DIO mode. Both brings no change. 

I.e. when submit some AP settings.
The serial dump of the JSON when saving settings looks correct:
```
ap req
{"ssid":"thingsAP","key":"","ip":"192.168.1.1"}handleFileRead: /index_en.html
handleFileRead: /index_en.html

```

But after restart the debug says:

```
{"wifiMode":"ap","debug":"full","baud":230400}
ap
Opening: /names.json
Successfully parsed /names.json
Subscription topic:things
Publishing topic:things
Name:another_thing
Setting up in AP Mode
Opening: /ap.json
Failed to parse /ap.json         <-------
{}
>dbg.WiFiMode(Open AP)
>dbg.IP(0)                   <-------
Opening: /protocol.json
Successfully parsed /protocol.json
>dbg.wsServer(81)
HTTP server started
```

**Comment by Vitorbnc** [comment]
It seems to be saving the right data. Right now I don't have any board available for testing, but as soon as I get my hands on one of those I'll try flashing this code with the latest libraries to see if the same error occurs here.

**Comment by Vitorbnc** [comment]
Hey, I've added a prebuilt binary, try flashing it and see if it works.
